---
# tasks file for postgres
# https://github.com/instructure/canvas-lms/wiki/Production-Start#database-installation-and-configuration
# https://www.postgresql.org/download/linux/ubuntu/
- name: Add postgresql key 
  apt_key:
    url: "{{ postgres_key }}"
  tags: pre_reqs

- name: Add postgresql repo 
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt bionic-pgdg main
  tags: pre_reqs

- name: Update cache and install required packages
  apt:
    name: "{{ packages }}"
    update_cache: True 
  tags: pre_reqs

# Configuring Postgresql 
# https://github.com/instructure/canvas-lms/wiki/Production-Start#configuring-postgres
# https://www.postgresql.org/docs/9.5/auth-pg-hba-conf.html

# TODO Change this configuration as it's not secure
- name: Modify postgresql.conf to make postgres listen to all connection requests on port 5432
  lineinfile:
    line: "listen_addresses = '*'"
    regexp: "^#listen_addresses"
    path: "{{ postgres_conf_dir}}/postgresql.conf"
  notify: restart postgres 
  tags: postgres_config

- name: Modify pg_hba.conf to allow all connections 
  template:
    src: pg_hba.j2
    dest: "{{ postgres_conf_dir }}/pg_hba.conf"
  notify: restart postgres 
  tags: postgres_config

# Set system username as postgres user 
- name: create default user 
  become_user: postgres 
  postgresql_user: 
    db: postgres
    name: "{{ username }}"
    role_attr_flags: SUPERUSER
  tags: postgres_config

- name: create canvas user
  become_user: postgres  
  postgresql_user:
    db: postgres 
    name: canvas 
    password: canvas123
    role_attr_flags: NOCREATEDB,NOSUPERUSER,NOCREATEROLE
  tags: postgres_config

- name: create canvas db 
  become_user: postgres 
  postgresql_db:
    name: canvas_production 
    owner: canvas 
  tags: postgres_config